In [2]:
import numpy as np
b = np.random.uniform(2, 3, 1)[0]

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [3]:
b

2.5411578233806655

In [5]:
np.random.uniform(2, 3)

2.6208923041817282

In [16]:
def sample_func(distribution_name, **dist_params):
   if distribution_name == "sym_pareto":
      a = dist_params.get("a", 1)
      samples = np.random.pareto(a, dist_params["size"])
      samples_copy = np.random.pareto(a, dist_params["size"])
      return samples - samples_copy + a
         
   if hasattr(np.random, distribution_name):
      dist_func = getattr(np.random, distribution_name)
      samples = dist_func(**dist_params)
      return samples + 1 if distribution_name == "pareto" else samples
   else:
      raise ValueError(f"Unsupported distribution: {distribution_name}")

In [18]:
np.random.pareto(1,10)

array([ 1.25189286,  1.15764594,  1.23839497,  0.13499405,  0.43333659,
        1.24783733,  0.82678368, 10.56075104,  0.11385448,  3.08372245])

In [8]:
a_ls = np.random.uniform(2, 3, 10)

In [10]:
a_ls

array([2.85511347, 2.19490564, 2.67818756, 2.05842771, 2.26915497,
       2.45504714, 2.84445579, 2.83178637, 2.99917666, 2.48506655])

In [17]:
arrays_list = []

for i in range(len(a_ls)):
    arrays_list.append(sample_func("pareto", size=2, a=a_ls[i]))
    sample_n = np.vstack(arrays_list).T

KeyError: -1

In [15]:
sample_n

array([[1.70090754, 2.18842562, 1.15733738, 1.51778965, 3.12520737,
        1.64968622, 1.17465221, 1.02896779, 1.01951291, 1.42872415],
       [1.59016605, 1.23117695, 1.92257239, 1.95430137, 1.22888732,
        1.35207172, 1.15547971, 1.11209308, 1.04731955, 1.05301194]])